# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2ef9a25a160dc22ccf7f39fcb47bc18d0e28fd6437834401ce0d834559567afa80678da4aeb824785da613461a2ce026f6c5c5fe90f73ec10db23ab4b59aa4a

test:
  secret_key_base: f617ee339cf6ae749ce508359b57562613ad3acaca23da4a2541644c04bc4a60f5f7552ca6ab04a2e2a2b6d4f287e864c9acf2c67cd0024a034fa60585e7037a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
